general.import = [
 "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.90
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
normal.family = "FiraCode Nerd Font"
size = 16

[selection]
save_to_clipboard = true
